## Error Cases

```{r}
library(autotest)
```

### Testing Variables

### Variable Not Found
```{r}
test_that('', {
  expect_equal(x, 1)
})
# AutoTestCaseError:
# Testing variable/expression:  x
# object 'x' not found
```


### Testing Functions

#### Function Not Found
```{r}
f <- 1
test_that('',{
  expect_equal(f(1), 1)
})
# AutoTestCaseError:
# Testing variable/expression:  f(1)
# could not find function "f"
```

#### Function Return Nothing
```{r}
f <- function(x) {}
test_that('',{
  expect_equal(f(1), 1)
})
# AutoTestCaseError:
# Testing variable/expression:  f(1)
# We expect your answer returns type "numeric", but it returns "NULL" instead.
# Do you forget to return something in your function definition?
```

#### Function Unused Arguments
```{r}
f <- function() 1
test_that('',{
  for (i in 1:5){
    expect_equal(f(i), i + 1)
  }
})
# AutoTestCaseError:
# Testing variable/expression:  f(i)
# unused argument (i)
```

### Result Not Equal

- Default error

```{r}
f <- function(x) ifelse(x > 5, x + 1, x)
test_that('',{
  for (i in 1:10){
    expect_equal(f(i), i + 1)
  }
})
# AutoTestCaseError:
# Testing variable/expression:  f(i)
# Your answer is 1, which is not equal to the correct answer 2
```

- Register error message.

```{r}
f <- function(x) ifelse(x > 5, x + 1, x)
test_that('',{
  for (i in 1:10){
    registerPreMsg('In testing f(%d)', i) # better
    expect_equal(f(i), i + 1)
  }
})
# AutoTestCaseError:
# Testing variable/expression:  f(i)
# In testing f(1)
# Your answer is 1, which is not equal to the correct answer 2
```

- Close tracing after register error message

```{r}
f <- function(x) ifelse(x > 5, x + 1, x)
test_that('',{
  for (i in 1:10){
    registerPreMsg('Tesing the function `f`, in testing f(%d)', i)
    expect_equal(f(i), i + 1, trace=FALSE) # close tracing
  }
})
# AutoTestCaseError:
# Tesing the function `f`, in testing f(1)
# Your answer is 1, which is not equal to the correct answer 2 
```
Compared with the error messages with previous two blocks, the line `Testing variable/expression: f(i)` is missing.
